export const SLIDER_FETCH_START = "SLIDER_FETCH_START";
export const SLIDER_FETCH_SUCCESS = "SLIDER_FETCH_SUCCESS";
export const SLIDER_FETCH_FAIL = "SLIDER_FETCH_FAIL";

export const MOVIE_FETCH_START = "MOVIE_FETCH_START";
export const MOVIE_FETCH_SUCCESS = "MOVIE_FETCH_SUCCESS";
export const MOVIE_FETCH_FAIL = "MOVIE_FETCH_FAIL";
